import React from 'react';
import { createClient } from '@supabase/supabase-js';
import { BarChart3, Users, Store, ClipboardCheck, CreditCard, Package, ShoppingCart, MessageSquare, Bell, Tags, Star, Flag, Settings, ChevronRight, ArrowLeft, Search, RefreshCw, Check, X, Eye, Send, Ban } from 'lucide-react';

const supabase=createClient('https://rcfjdgusrroiemsdevei.supabase.co','sb_publishable_RWsFiyYBIWtW5jWzXaEUZA_O30fbkN-',{auth:{persistSession:true,autoRefreshToken:true}});
const fm=supabase.schema('farm_market');
const money=n=>new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(Number(n)||0);
const sections=[
 ['overview','Overview',BarChart3,'Marketplace performance and pending work'],
 ['users','Users',Users,'Registered Farm Market accounts'],
 ['sellers','Sellers',Store,'Seller accounts and status'],
 ['applications','Applications',ClipboardCheck,'Seller applications awaiting review'],
 ['payments','Payments',CreditCard,'Seller activation payment information'],
 ['listings','Listings',Package,'Marketplace listings and approvals'],
 ['orders','Orders',ShoppingCart,'Marketplace order requests'],
 ['messages','Messages',MessageSquare,'Conversations and user reports'],
 ['notifications','Notifications',Bell,'Send and review platform notifications'],
 ['categories','Categories',Tags,'Categories currently used by listings'],
 ['reviews','Reviews',Star,'Marketplace feedback'],
 ['reports','Reports',Flag,'Reported listings and users'],
 ['settings','Settings',Settings,'Marketplace administration settings']
];
const tableFor={users:'profiles',sellers:'sellers',applications:'sellers',payments:'sellers',listings:'listings',orders:'orders',messages:'conversations',reviews:'reviews',reports:'reports'};

export default function AdminDashboard({go,stats={},profile,notify}){
 const [active,setActive]=React.useState('overview');
 const [rows,setRows]=React.useState([]); const [loading,setLoading]=React.useState(false); const [error,setError]=React.useState(''); const [search,setSearch]=React.useState(''); const [refresh,setRefresh]=React.useState(0);
 const current=sections.find(x=>x[0]===active)||sections[0]; const Icon=current[2];
 React.useEffect(()=>{let alive=true; const load=async()=>{if(active==='overview'||active==='settings'||profile?.role!=='admin'){setRows([]);return} setLoading(true);setError(''); const table=active==='categories'?'listings':tableFor[active]; let q=fm.from(table).select('*').order('created_at',{ascending:false}).limit(100); if(active==='applications')q=q.eq('status','pending'); if(active==='payments')q=q; if(active==='listings')q=q; if(active==='reports')q=q; const r=await q; if(alive){if(r.error){setError(r.error.message);setRows([])}else setRows(r.data||[]);setLoading(false)}};load();return()=>{alive=false}},[active,refresh,profile?.role]);
 const choose=id=>{setSearch('');setActive(id)};
 const act=async(row,action)=>{let table=tableFor[active],patch=null;
  if(active==='applications'||active==='sellers'){patch=action==='approve'?{status:'active'}:action==='reject'?{status:'rejected'}:action==='suspend'?{status:'suspended'}:null}
  if(active==='payments'){patch=action==='approve'?{activation_payment_status:'paid'}:action==='reject'?{activation_payment_status:'rejected'}:null}
  if(active==='listings'){patch=action==='approve'?{status:'approved'}:action==='reject'?{status:'rejected'}:action==='hide'?{status:'hidden'}:null}
  if(active==='reports'){patch=action==='resolve'?{status:'resolved'}:action==='dismiss'?{status:'dismissed'}:null}
  if(active==='orders'){patch=action==='accept'?{status:'accepted'}:action==='reject'?{status:'rejected'}:action==='cancel'?{status:'cancelled'}:null}
  if(!patch)return; const r=await fm.from(table).update(patch).eq('id',row.id); if(r.error)notify?.(r.error.message);else{notify?.('Updated successfully');setRefresh(x=>x+1)}};
 if(profile?.role!=='admin')return <section className="wrap page"><div className="panel center"><Shield/><h2>Administrator access required</h2><p>This area is restricted to Farm Market administrators.</p></div></section>;
 const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
 return <section className="adminPage"><div className="adminHero"><div><span>FARMMARKET UGANDA · CONTROL CENTRE</span><h1>Super Admin</h1><p>Manage the marketplace from one protected workspace.</p></div><button onClick={()=>go('dashboard')}><ArrowLeft/> My account</button></div>
  <div className="adminStats"><Stat n={stats.users??'—'} t="Users"/><Stat n={stats.sellers??'—'} t="Sellers"/><Stat n={stats.listings??'—'} t="Listings"/><Stat n={stats.orders??'—'} t="Orders"/><Stat n={stats.pending??'—'} t="Pending"/><Stat n={stats.revenue??'UGX 0'} t="Revenue"/></div>
  <div className="adminShell"><aside className="adminSidebar">{sections.map(([id,title,I])=><button className={active===id?'selected':''} key={id} onClick={()=>choose(id)}><I/><span>{title}</span><ChevronRight/></button>)}</aside>
   <div className="adminMain"><div className="adminSectionHead"><div><Icon/><span>ADMINISTRATION</span><h2>{current[1]}</h2><p>{current[3]}</p></div><div className="adminHeadActions">{active!=='overview'&&<button className="adminBack" onClick={()=>choose('overview')}>← Overview</button>}{active!=='overview'&&active!=='settings'&&<button className="adminIconBtn" onClick={()=>setRefresh(x=>x+1)} title="Refresh"><RefreshCw/></button>}</div></div>
    {active==='overview'?<Overview stats={stats} choose={choose}/>:active==='categories'?<Categories rows={rows} notify={notify}/>:active==='notifications'?<Notifications notify={notify}/>:active==='settings'?<SettingsPanel/>:<DataManager active={active} rows={filtered} loading={loading} error={error} search={search} setSearch={setSearch} act={act}/>} 
   </div></div>
  <nav className="adminMobileNav">{sections.slice(0,5).map(([id,title,I])=><button className={active===id?'active':''} key={id} onClick={()=>choose(id)}><I/><small>{title}</small></button>)}</nav></section>
}
function Shield(){return <Ban/>} function Stat({n,t}){return <div className="adminStat"><b>{n}</b><span>{t}</span></div>}
function Overview({stats,choose}){return <><div className="adminQuick"><Quick title="Seller applications" value={stats.pending??0} text="Waiting for review" id="applications" choose={choose}/><Quick title="Payment verification" value={stats.payments??0} text="Seller payment records" id="payments" choose={choose}/><Quick title="Listings" value={stats.listings??0} text="Marketplace listings" id="listings" choose={choose}/><Quick title="Reports" value={stats.reports??0} text="Issues requiring attention" id="reports" choose={choose}/></div><div className="adminActivity"><h3>Administration centre</h3><p>Every card below opens a real management screen. Changes made in these screens are written to Supabase.</p><div className="adminFeatureGrid">{sections.slice(1).map(([id,title,I,text])=><button key={id} onClick={()=>choose(id)}><I/><div><b>{title}</b><span>{text}</span></div><ChevronRight/></button>)}</div></div></>}
function Quick({title,value,text,id,choose}){return <button className="adminQuickCard" onClick={()=>choose(id)}><span>{title}</span><strong>{value}</strong><small>{text}</small><ChevronRight/></button>}
function DataManager({active,rows,loading,error,search,setSearch,act}){return <div className="adminData"><div className="adminToolbar"><div className="adminSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${active}...`}/></div><span>{rows.length} record{rows.length===1?'':'s'}</span></div>{loading?<div className="adminLoading">Loading {active}…</div>:error?<div className="adminError">{error}</div>:rows.length===0?<div className="adminEmpty"><Eye/><h3>No records</h3><p>There are currently no {active} records matching your search.</p></div>:<div className="adminRows">{rows.map(r=><AdminRow key={r.id} active={active} row={r} act={act}/>)}</div>}</div>}
function AdminRow({active,row,act}){const label=active==='users'?(row.full_name||row.email||row.id):active==='sellers'?(row.farm_name||row.business_name||row.phone||row.id):active==='applications'?(row.farm_name||row.business_name||row.phone||row.id):active==='payments'?(row.transaction_id||row.activation_payment_status||row.farm_name||row.id):active==='listings'?(row.title||row.name||row.id):active==='orders'?(money(row.total||row.amount)||row.id):active==='messages'?(row.subject||row.id):active==='reviews'?(row.comment||row.rating||row.id):(row.reason||row.title||row.id); const status=row.status||row.activation_payment_status||'—'; return <div className="adminRow"><div className="adminRowMain"><b>{String(label)}</b><span>Status: {String(status)}</span>{row.email&&<small>{row.email}</small>}{row.transaction_id&&<small>Transaction ID: {row.transaction_id}</small>}{row.phone&&<small>Phone: {row.phone}</small>}</div><div className="adminRowActions">{(active==='applications'||active==='sellers')&&row.status==='pending'&&<><button className="approve" onClick={()=>act(row,'approve')}><Check/> Approve</button><button className="reject" onClick={()=>act(row,'reject')}><X/> Reject</button></>}{active==='payments'&&row.activation_payment_status!=='paid'&&<><button className="approve" onClick={()=>act(row,'approve')}><Check/> Mark paid</button><button className="reject" onClick={()=>act(row,'reject')}><X/> Reject</button></>}{active==='listings'&&row.status==='pending'&&<><button className="approve" onClick={()=>act(row,'approve')}><Check/> Approve</button><button className="reject" onClick={()=>act(row,'reject')}><X/> Reject</button></>}{active==='listings'&&row.status==='approved'&&<button className="reject" onClick={()=>act(row,'hide')}><Ban/> Hide</button>}{active==='reports'&&row.status==='open'&&<button className="approve" onClick={()=>act(row,'resolve')}><Check/> Resolve</button>}{active==='reports'&&row.status==='open'&&<button className="reject" onClick={()=>act(row,'dismiss')}><X/> Dismiss</button>}{active==='orders'&&row.status==='pending'&&<><button className="approve" onClick={()=>act(row,'accept')}><Check/> Accept</button><button className="reject" onClick={()=>act(row,'reject')}><X/> Reject</button></>}</div></div>}
function Categories({rows}){const cats=[...new Set(rows.map(x=>x.category).filter(Boolean))].sort();return <div className="adminData"><div className="adminCategoryNote">Categories are currently derived from the categories used by approved listings. Add/edit category storage can be enabled once a dedicated categories table is created.</div>{cats.length?<div className="adminRows">{cats.map(c=><div className="adminRow" key={c}><div className="adminRowMain"><b>{c}</b><span>Used by marketplace listings</span></div></div>) :<div className="adminEmpty"><Tags/><h3>No categories yet</h3><p>Create listings with categories and they will appear here.</p></div>}</div>}
function Notifications({notify}){const[title,setTitle]=React.useState('');const[body,setBody]=React.useState('');const[recipient,setRecipient]=React.useState('');const[busy,setBusy]=React.useState(false);const send=async e=>{e.preventDefault();setBusy(true);const r=await fm.from('notifications').insert({user_id:recipient.trim(),title:title.trim(),body:body.trim()});setBusy(false);if(r.error)return notify?.(r.error.message);setTitle('');setBody('');setRecipient('');notify?.('Notification sent');};return <div className="adminData"><form className="adminForm" onSubmit={send}><h3>Send a notification</h3><p>Enter a Supabase profile/user ID to send a direct notification.</p><label>Recipient user ID<input required value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Message<textarea required rows="4" value={body} onChange={e=>setBody(e.target.value)}/></label><button className="approve" disabled={busy}><Send/> {busy?'Sending…':'Send notification'}</button></form></div>}
function SettingsPanel(){return <div className="adminData"><div className="adminSettingsCard"><Settings/><h3>Platform settings</h3><p>Farm Market uses Supabase authentication, the <b>farm_market</b> schema and the connected Vercel frontend.</p><p>Seller activation fee: <strong>UGX 15,000</strong>.</p><p>Admin access is controlled by the <strong>profiles.role = admin</strong> value.</p><p>Payment gateway automation can be added here once a payment provider is connected.</p></div></div>}
